BEGIN
    FOR i IN 1..200 LOOP
    INSERT INTO SBOARD(SEQ, TITLE, CONTENT, HIT, REGDATE, NAME, PASS, GROUPS, STEP, LEVELS) VALUES(SBOARD_SEQ.NEXTVAL, '제목 '||i, '내용 '||i, 0, SYSDATE, 'Admin','pass', 0, 0, 0);
    END LOOP;
END;
/
